#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Corps du rapport — ReportLab (route Report du skill pdf).
Conformité : TocDocTemplate + multiBuild, install_font_fallback, tables 100 % Paragraph,
colWidths proportionnels <= available, CondPageBreak 25 % avant H1, pas de saut forcé,
footer romain (TOC) puis arabe réinitialisé, palette cascade seed 42."""

import os, sys, hashlib

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, Image, KeepTogether, CondPageBreak, HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from PIL import Image as PILImage

import content_fr as C

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade, seed 42) ━━
from reportlab.lib import colors
PAGE_BG       = colors.HexColor('#f5f5f4')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#ebeae8')
TABLE_STRIPE  = colors.HexColor('#ededeb')
HEADER_FILL   = colors.HexColor('#4e4732')
COVER_BLOCK   = colors.HexColor('#746c56')
BORDER        = colors.HexColor('#c5bfac')
ICON          = colors.HexColor('#a48e4b')
ACCENT        = colors.HexColor('#92761f')
ACCENT_2      = colors.HexColor('#3aa0c2')
TEXT_PRIMARY  = colors.HexColor('#151513')
TEXT_MUTED    = colors.HexColor('#7e7c74')
SEM_SUCCESS   = colors.HexColor('#529067')
SEM_WARNING   = colors.HexColor('#8c7443')
SEM_ERROR     = colors.HexColor('#a25b54')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ---------------- Fontes ----------------
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ---------------- Géométrie ----------------
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'body.pdf')

# ---------------- Styles ----------------
BODY = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                      alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=9)
LEAD = ParagraphStyle('Lead', parent=BODY, fontSize=11, leading=17.5)
H1 = ParagraphStyle('H1x', fontName='FreeSerif', fontSize=20, leading=25, alignment=TA_LEFT,
                    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4)
H2 = ParagraphStyle('H2x', fontName='FreeSerif', fontSize=14.5, leading=19, alignment=TA_LEFT,
                    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=7)
BULLET = ParagraphStyle('Bul', parent=BODY, alignment=TA_LEFT, leftIndent=14,
                        firstLineIndent=0, spaceAfter=8, bulletIndent=2)
CAPTION = ParagraphStyle('Cap', fontName='FreeSerif', fontSize=8.5, leading=11.5,
                         alignment=TA_CENTER, textColor=TEXT_MUTED, spaceBefore=0, spaceAfter=0)
QUOTE = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5, leading=16,
                       alignment=TA_LEFT, leftIndent=24, textColor=TEXT_PRIMARY, spaceBefore=6, spaceAfter=6)
TH = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=12.5,
                    alignment=TA_LEFT, textColor=colors.white)
TC = ParagraphStyle('TC', fontName='FreeSerif', fontSize=8.8, leading=11.8,
                    alignment=TA_LEFT, textColor=TEXT_PRIMARY)
TCC = ParagraphStyle('TCC', parent=TC, alignment=TA_CENTER)
STAT_BIG = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=21, leading=24,
                          textColor=ACCENT, alignment=TA_CENTER)
STAT_LBL = ParagraphStyle('StatLbl', fontName='FreeSerif', fontSize=8.2, leading=10.5,
                          textColor=TEXT_MUTED, alignment=TA_CENTER)
TOC_TITLE = ParagraphStyle('TocTitle', fontName='FreeSerif', fontSize=17, leading=22,
                           textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=14)

# ---------------- Doc template avec TOC ----------------
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # Page affichée = page interne - 1 (la page 1 interne est la TOC en romain)
            self.notify('TOCEntry', (level, text, self.page - 1, key))

def on_page(canvas, doc):
    canvas.saveState()
    # En-tête : titre + filet accent
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, C.TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Pied : auteur + numéro (TOC en romain, corps en arabe réinitialisé à 1)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'Z.ai — Audit ScolaGestion V4')
    num = 'i' if doc.page == 1 else str(doc.page - 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, num)
    canvas.restoreState()

# ---------------- Aides ----------------
def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

MAX_KEEP_HEIGHT = A4[1] * 0.4
def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, AVAIL_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def h1_block(num, title, first_flowable=None):
    """Chapitre : saut conditionnel (25 %), titre 20pt + filet accent, lié au 1er paragraphe."""
    items = [add_heading('%d. %s' % (num, title), H1, level=0),
             HRFlowable(width='100%', color=ACCENT, thickness=1.2, spaceBefore=0, spaceAfter=12)]
    if first_flowable is not None:
        items.append(first_flowable)
    return [CondPageBreak(AVAIL_H * 0.25), Spacer(1, 18)] + safe_keep_together(items)

def P(text, style=BODY):
    return Paragraph(text, style)

def bullets(items):
    out = []
    for head, body in items:
        out.append(P('• <b>%s</b> — %s' % (head, body), BULLET))
    return out

def styled_table(data, ratios, header=True, cell_styles=None, font_size=None):
    """Table : cellules 100 % Paragraph, largeur proportionnelle, en-tête HEADER_FILL."""
    th = TH if font_size is None else ParagraphStyle('TH%d' % font_size, parent=TH, fontSize=font_size + 0.7, leading=font_size + 3.3)
    tc = TC if font_size is None else ParagraphStyle('TC%d' % font_size, parent=TC, fontSize=font_size, leading=font_size + 3)
    rows = []
    for i, row in enumerate(data):
        cells = []
        for j, cell in enumerate(row):
            if i == 0 and header:
                cells.append(Paragraph('<b>%s</b>' % cell, th))
            else:
                st = tc
                if cell_styles and (i, j) in cell_styles:
                    st = cell_styles[(i, j)]
                cells.append(Paragraph(cell, st))
        rows.append(cells)
    widths = [r * AVAIL_W for r in ratios]
    assert sum(widths) <= AVAIL_W + 0.5, 'table trop large: %.1f > %.1f' % (sum(widths), AVAIL_W)
    t = Table(rows, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5.5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD if i % 2 == 1 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    return t

def table_block(title_txt, data, ratios, caption=None, font_size=None, cell_styles=None):
    out = [Spacer(1, 16)]
    t = styled_table(data, ratios, cell_styles=cell_styles, font_size=font_size)
    if len(data) <= 9:
        out.extend(safe_keep_together([t]))
    else:
        out.append(t)
    if caption:
        out.append(Spacer(1, 6))
        out.append(P(caption, CAPTION))
    out.append(Spacer(1, 14))
    return out

def stat_callouts(stats):
    """Rangée de 4 encadrés chiffrés (data-to-ink)."""
    row_vals = [Paragraph('<b>%s</b>' % v, STAT_BIG) for v, _ in stats]
    row_lbls = [Paragraph(l, STAT_LBL) for _, l in stats]
    t = Table([row_vals, row_lbls], colWidths=[AVAIL_W / len(stats)] * len(stats), hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('INNERGRID', (0, 0), (-1, -1), 0.75, BORDER),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('TOPPADDING', (0, 0), (-1, 0), 9),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 9),
        ('TOPPADDING', (0, 1), (-1, 1), 1),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 1),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return [Spacer(1, 14), t, Spacer(1, 16)]

def callout_box(text):
    t = Table([[Paragraph(text, ParagraphStyle('CO', parent=BODY, alignment=TA_LEFT, spaceAfter=0))]],
              colWidths=[AVAIL_W * 0.96], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 9),
    ]))
    return [Spacer(1, 10), t, Spacer(1, 12)]

def embed_image(path, max_width, max_height):
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(max_width / ow if ow > max_width else 1.0,
                max_height / oh if oh > max_height else 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)

# ================= Construction du story =================
story = []

# --- TOC (page 1 interne, romaine) ---
story.append(Paragraph('<b>Table des matières</b>', TOC_TITLE))
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOCH1', fontName='FreeSerif', fontSize=11.5, leading=17, leftIndent=6, textColor=TEXT_PRIMARY),
]
story.append(toc)
story.append(PageBreak())

# --- 1. Synthèse exécutive ---
story.extend(h1_block(1, 'Synthèse exécutive', P(C.S1_P[0], LEAD)))
story.extend(stat_callouts(C.S1_CALLOUTS))
for para in C.S1_P[1:]:
    story.append(P(para))
story.extend(callout_box(
    '<b>Verdict global :</b> plateforme de démonstration riche (schéma exceptionnel de 162 modèles, '
    'base intègre, interface complète, zéro erreur technique) mais <b>non opérationnelle</b> : sécurité '
    'inexistante, intégrité des données non garantie (8/8 tests en échec), et 73,5 % du schéma '
    'exploité en lecture seule.'))

# --- 2. Méthodologie ---
story.extend(h1_block(2, 'Méthodologie et périmètre', P(C.S2_P[0])))
for para in C.S2_P[1:]:
    story.append(P(para))
story.extend(table_block(None, C.S2_SOURCES, [0.30, 0.26, 0.44],
                         caption='Tableau 1 — Sources auditées et leur contribution au présent rapport'))

# --- 3. Acquis confirmés ---
story.extend(h1_block(3, 'Acquis confirmés', P(C.S3_P[0])))
for para in C.S3_P[1:]:
    story.append(P(para))

# --- 4. Faille 1 : sécurité ---
story.extend(h1_block(4, 'Faille 1 — Sécurité et authentification inexistantes', P(C.S4_P[0])))
for para in C.S4_P[1:]:
    story.append(P(para))
story.extend(table_block(None, C.S4_TABLE, [0.28, 0.42, 0.30],
                         caption='Tableau 2 — Exigences de sécurité minimales et état vérifié'))

# --- 5. Faille 2 : intégrité ---
story.extend(h1_block(5, 'Faille 2 — Intégrité des données : huit échecs prouvés', P(C.S5_P[0])))
for para in C.S5_P[1:]:
    story.append(P(para))
story.extend(table_block(None, C.S5_TESTS, [0.17, 0.30, 0.41, 0.12], font_size=8.2,
                         caption='Tableau 3 — Résultats des huit tests d\'intégrité exécutés en base (réplication exacte du code des actions)'))
for para in C.S5_P2:
    story.append(P(para))
story.extend(stat_callouts([('8/8', 'tests en échec'), ('30 000 XOF', 'perdus sur 60 000 (T2)'),
                            ('-150', 'unités de stock atteintes (T3)'), ('0', 'notification créée (T8)')]))

# --- 6. Faille 3 : couverture ---
story.extend(h1_block(6, 'Faille 3 — Couverture fonctionnelle en vitrine', P(C.S6_P[0])))
for para in C.S6_P[1:]:
    story.append(P(para))
# Graphique (bloc autonome + légende, KeepTogether limité)
img = embed_image(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'chart-usage.png'),
                  AVAIL_W, A4[1] * 0.35)
story.append(Spacer(1, 24))
story.extend(safe_keep_together([img, Spacer(1, 8),
                                 P('Figure 1 — Répartition des 162 modèles Prisma selon leur usage dans le code applicatif', CAPTION)]))
story.append(Spacer(1, 18))
story.extend(table_block(None, C.S6_TABLE, [0.19, 0.43, 0.38], font_size=8.6,
                         caption='Tableau 4 — Catégories de modèles et leurs conséquences fonctionnelles'))

# --- 7. Failles secondaires ---
story.extend(h1_block(7, 'Failles secondaires et code mort', P(C.S7_INTRO[0])))
story.extend(bullets(C.S7_BULLETS))

# --- 8. Référentiel ---
story.extend(h1_block(8, 'Référentiel de gestion scolaire complète', P(C.S8_INTRO[0])))
LEVEL_STYLE = {
    'Fonctionnel': ParagraphStyle('LvOK', parent=TC, textColor=SEM_SUCCESS, alignment=TA_CENTER),
    'Partiel': ParagraphStyle('LvP', parent=TC, textColor=SEM_WARNING, alignment=TA_CENTER),
    'Vitrine': ParagraphStyle('LvV', parent=TC, textColor=TEXT_MUTED, alignment=TA_CENTER),
    'Absent': ParagraphStyle('LvA', parent=TC, textColor=SEM_ERROR, alignment=TA_CENTER),
}
cell_styles = {}
for i, row in enumerate(C.S8_MATRIX):
    if i > 0:
        cell_styles[(i, 1)] = LEVEL_STYLE.get(row[1], TC)
story.extend(table_block(None, C.S8_MATRIX, [0.27, 0.12, 0.61], font_size=8.4, cell_styles=cell_styles,
                         caption='Tableau 5 — Matrice de complétude par domaine (niveaux : Fonctionnel, Partiel, Vitrine, Absent)'))

# --- 9. Plan de remédiation ---
story.extend(h1_block(9, 'Plan de remédiation priorisé', P(C.S9_INTRO[0])))
story.extend(table_block(None, C.S9_PLAN, [0.20, 0.64, 0.16], font_size=8.4,
                         caption='Tableau 6 — Correctifs ordonnés par risque décroissant, avec effort estimé'))

# --- 10. Conclusion ---
story.extend(h1_block(10, 'Conclusion et verdict', P(C.S10_P[0])))
for para in C.S10_P[1:]:
    story.append(P(para))
story.extend(callout_box(
    '<b>Prochaine étape recommandée :</b> engager le lot P0 (authentification NextAuth branchée sur le '
    'RBAC seedé, $transaction sur les quatre flux concurrents, validation zod, purge des secrets). '
    'Les huit scénarios T1 à T8 du présent rapport constituent la suite de non-régression naturelle '
    'pour valider chaque correctif.'))

# ================= Construction =================
doc = TocDocTemplate(OUT, pagesize=A4,
                     leftMargin=MARGIN, rightMargin=MARGIN,
                     topMargin=MARGIN, bottomMargin=MARGIN,
                     title=C.TITLE, author=C.AUTHOR, creator='Z.ai', subject=C.SUBJECT)
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('body.pdf généré:', OUT)
